
public enum TokenType
{
    INFLICT_STATUS,
    FLAT_STAT_CHANGE,
    MULT_STAT_CHANGE,
    SUPPORT_EFFECT_UP,
    CRIT,
    TAUNT,
    STUN,
    EVADE,
    LIFESTEAL,
    REFLECT
}

public enum TokenConsumptionType
{
    CONSUME_ON_SUPPORT,
    CONSUME_PRE_ATTACK,
    CONSUME_ON_MAG_ATTACK,
    CONSUME_ON_PHYS_ATTACK,
    CONSUME_ON_MAG_DEFEND,
    CONSUME_ON_PHYS_DEFEND,
    CONSUME_ON_HEAL,
    CONSUME_ON_MANA_ALTER,
    CONSUME_ON_MOVE,
    CONSUME_ON_NEXT_TURN
}
